env:
  - TARGET=qvm-lib
  - TARGET=qvm-app

services:
  - docker

script:
  - echo ${TARGET}
  - docker build -t rigetti/qvm:${TRAVIS_COMMIT} .
  - docker run --rm --entrypoint=make rigetti/quilc:${TRAVIS_COMMIT} test-${TARGET}
  - docker rmi rigetti/quilc:${TRAVIS_COMMIT}
